language: go
go:
  - "1.10.x"
script:
  - go get github.com/jinzhu/configor
  - go get github.com/jinzhu/gorm
  - go get github.com/sirupsen/logrus
  - go get github.com/go-kit/kit
  - go get google.golang.org/grpc
  - go get github.com/satori/go.uuid
  - go test ./strings