language: go
go:
  - "1.10.x"
script:
  - go test ./strings
  - go test ./set
  - go test ./algorithm
notifications:
  email:
    recipients:
      - tedforv@outlook.com
    on_success: change
    on_failure: always